### ISSUE TITLE
Pixelated/dithered widgets issue.

### ISSUE THREAD

**Issue by csharphater** [rdbende/Sun-Valley-ttk-theme#100]
Hey man! Love the theme. 
Decided to open an issue because I had to rollback the spritesheets.
I don't think you noticed, but the new version that you uploaded looks compressed or messed up.
Take a look.

![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/133157883/3514ece7-b51c-49a4-b11e-09608ab0e9bf)
This is the new spritesheet.
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/133157883/f76ea35f-767f-4132-89cc-8b4c6c685036)
This is the old one.

There hasn't been an issue about it yet, so I decided to write this, hoping you could fix it so no one will face this issue :)

**Comment by rdbende** [comment]
Shit. I published 3 bugfix releases before I came abroad, but I forgot to actually try them out.

Thank you for noticing this! Hopefully I can fix it from my phone, or else I'd need someone to fix it.

**Comment by csharphater** [comment]
I understand man, working abroad is a mess! I'm glad I could help you notice.

**Comment by rdbende** [comment]
I'd be grateful, if somebody could help me with this, because developing from a phone is a nightmare. I can't figure out what's wrong, and what might cause the issue.

How to do it:
- `git clone` the repo
- `npm install` inside `src/`
- Experiment with some stuff (might even change versions in `packages.json` and the reinstall packages.
- `node spritesheet_generator.js`
- See if pixelatedness and ditheredness gets fixed.

**Comment by csharphater** [comment]
Oh it's not the spritesheet generator, it's the image itself!
I myself have been able to fix the issue by looking at the commit logs.

https://github.com/rdbende/Sun-Valley-ttk-theme/commit/15fe9bbb98d42bb8b354efc7fadbc8893d73ce5d

From there, I just downloaded the originals & replaced them inside the sv-ttk/theme folder

**Comment by rdbende** [comment]
Sooo. Turns out I actually fixed it, just caching got in the way, and the preview was outdated. Will publish a release ASAP.

**Comment by rdbende** [comment]
Ok, I managed to fix it.

**Comment by rdbende** [comment]
Thankfully a lotta stuff is automated here, which made fixing it from a phone way easier. I don't know my Pypi password anyway :D
