### ISSUE TITLE
[Question]: How did you make a dark theme toggle? Was it a widget or an image button?

### ISSUE THREAD

**Issue by mak448a** [rdbende/Sun-Valley-ttk-theme#105]
Title

**Comment by rdbende** [comment]
You can use the `Switch.TCheckbutton` style

```py
switch = ttk.Checkbutton(text="I'm a toggle switch", style="Switch.TCheckbutton")
```

The original example can be found [here](https://github.com/rdbende/Sun-Valley-ttk-examples/blob/master/Widget%20demo/main.py)

**Comment by mak448a** [comment]
Thanks

**Comment by mak448a** [comment]
Also, how do I put the text on the left side?
