### ISSUE TITLE
Menubar colour 

### ISSUE THREAD

**Issue by cmsethi** [rdbende/Sun-Valley-ttk-theme#116]
Hi, with the Sun Valley (black) theme, the Menubar colour doesn't change; even on the ttk theme document page, I haven't found anything regarding the menubar color.
'ttk.Menu' not working, Please let me know if there is a suitable workaround. Thanks

**Comment by rdbende** [comment]
I suppose you're on Windows?
If yes, sadly the color of the menubar can't be changed on Windows.
