### ISSUE TITLE
Remove four black dots at the corners of the button

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#117]
https://github.com/rdbende/Sun-Valley-messageboxes/pull/4#issuecomment-1575635667

Example:
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/fc09931b-4f1d-4e91-8ed7-c82b9f717296)

**Comment by rdbende** [comment]
I think you misunderstood something in that comment. I won't remove the sharp corners conpletely, but will change the background colors of the messagebox, so when you use `-transparentcolor`, it won't affect the buttons.

**Comment by littlewhitecloud** [comment]
Sorry, but why there is four black dots?

**Comment by rdbende** [comment]
It's because the corners are rounded. However Tk doesn't support transparency, so there needs to something behind those corners, which is what you call the "four black dots".

**Comment by littlewhitecloud** [comment]
Thanks! Closing this issue
