### ISSUE TITLE
Open frame destroy frame and apply the theme

### ISSUE THREAD

**Issue by Snipeur060** [rdbende/Sun-Valley-ttk-theme#124]
Hi, we get an error when we open the window and close it (a multi-window application).

To fix this I added in the init instead of return
`cls.tcl = _get_default_root()`
(old in blue new is the line after)
<img width="357" alt="image" src="https://github.com/rdbende/Sun-Valley-ttk-theme/assets/61784407/a431bd1e-658f-463d-bd97-1240db53d90b">
Error with the return :
<img width="502" alt="image" src="https://github.com/rdbende/Sun-Valley-ttk-theme/assets/61784407/320045a7-b87f-4e05-820e-aa90acd93d26">

But this fix destroys most other features

**Comment by rdbende** [comment]
Hi,

So the problem basically is that you are not meant to create multiple `tkinter.Tk` instances (for multi-window apps, use a `tkinter.Toplevel`), and therefore `sv-ttk` doesn't account for that scenario. For more info, see: https://github.com/rdbende/Sun-Valley-ttk-theme/issues/72

**Comment by Snipeur060** [comment]
I would normally use classes etc but I have to use functions and put that in open/destroy (a project for studies and it's a constraint)

So no alternative ?

**Comment by rdbende** [comment]
You can actually pass in the window you want the theme to be applied on with the `root` argument. It should work that way.

**Comment by Snipeur060** [comment]
So the main frame is for example defined as root 
If I open the f1 frame (an other frame defined after), the frame will use the root theme?

**Comment by rdbende** [comment]
If you create another `tkinter.Tk` instance, it will not automatically use the theme, but you can pass it to the `set_theme` function like so: `sv_ttk.use_dark_theme(root=root2)`. And that way it will not give an error.

**Comment by Snipeur060** [comment]
This doesn't work for me. I'm going to use my "bidouillage", I only need to display the dark theme and I work with that.
But thanks for the help which I appreciate
