### ISSUE TITLE
Tree view indentation

### ISSUE THREAD

**Issue by Zombee0804** [rdbende/Sun-Valley-ttk-theme#13]
I'm creating a personal application using this theme and trying to implement a treeview. I am not sure why, but the children items in the tree are not indented from their parents. I have attached an image showing this.

![image](https://user-images.githubusercontent.com/79462745/147281509-9c6540d2-e4ac-492a-9978-3b2527ccc58a.png)

I am new to Tk/Ttk so I am not sure if the indentation has to be implemented manually or not, but it seems to be automatic judging by things online. I have looked at the documentation for ttk and can't find any option to toggle. Also looked through the theme files and tried tweaking them (I do not know tcl) but nothing seems to be working.

Any help would be appreciated, thanks.

**Comment by rdbende** [comment]
Tk indents children automatically. I had a quick look at your code and didn't find anything, but there must be a problem when you set the item parents.
![image](https://user-images.githubusercontent.com/77941087/147295505-c3c252da-20b7-40af-8a27-3ba9e9b8b315.png)

**Comment by Zombee0804** [comment]
I found the issue. I wasn't setting the 'text' value when inserting items into the tree. I assumed that all columns were filled by the values property but that was not the case, so the '#0' column was empty.

**Comment by rdbende** [comment]
Yeah, column #0 behaves pretty weird, from both programming and a theme development perspective.
