### ISSUE TITLE
Theme doesn't apply itself

### ISSUE THREAD

**Issue by im-coder-lg** [rdbende/Sun-Valley-ttk-theme#17]
Hi,

I am trying to develop a simple popup window for [TimerX](https://github.com/TimerX-App/TimerX).
Development code [here](https://github.com/TimerX-App/TimerX-Update-Test/tree/im-coder-lg/simple-gui). I accomplished so much in that, so I tried adding the Ttk to it.
Yeah, I know it's not a real popup yet, but back to the issue.
I got the theme code, v1.0.0 if you were going to ask and added it, did all the extravaganzas to set it up. However, on Replit as well as my local Windows 7 machine(which can very well display the theme), it doesn't apply itself. Do you have a fix for this? Or is the solution simple?

Edit: Changed to the latest source code but still fails.

**Comment by rdbende** [comment]
Of course, it does not apply itself, since you just imported it but didn't specify which theme it should use. You have to use this call to set the theme:

```python
app.tk.call("set_theme", "dark")
```

**Comment by im-coder-lg** [comment]
It seems to work now, thanks! I knew the solution was simple. Too quick to see that lol.
