### ISSUE TITLE
Cannot install with pip / requirements.txt yet

### ISSUE THREAD

**Issue by PicoPlanetDev** [rdbende/Sun-Valley-ttk-theme#2]
Currently, attempting to install this theme through the Github link with pip or a requirements.txt file results in an error:
`ERROR: File "setup.py" not found for legacy project Sun-Valley-ttk-theme from git+git://github.com/rdbende/Sun-Valley-ttk-theme@master#egg=Sun-Valley-ttk-theme (from -r requirements.txt (line 7)).`
This theme can therefore only be installed by placing it manually, resulting in more difficulty for the end user.
Are there any automatic installation options for this?

Thanks :-)

**Comment by rdbende** [comment]
**This is not a python module, just a simple tcl script.**

So you can't install it via pip. Ttk themes like this are not usually installed and imported, but they are included with the program and used that way. The license allows you to do so, even with modifications.
