### ISSUE TITLE
theme/light/radio-rest.png is corrupted

### ISSUE THREAD

**Issue by PicoPlanetDev** [rdbende/Sun-Valley-ttk-theme#22]
When trying to initialize Tkinter, the following error is thrown:

```
root.tk.call("source", "sun-valley.tcl")
_tkinter.TclError: couldn't recognize data in image file "./theme/light/radio-rest.png"
```

Explorer is unable to preview `radio-rest.png` and paint.net cannot open it.

The same issue is not observed with the dark theme.

**Comment by rdbende** [comment]
I cannot reproduce the error. I can open it in Tkinter, GIMP, Gwenwiev, Forefox, Brave, it works just fine everywhere.
Exported the image again from Inkscape, but `diff radio-rest.png radio-rest-new.png` says there's no difference.

**Comment by PicoPlanetDev** [comment]
Thank you for checking that.
I just resolved the error by going to the `radio-rest.png` page [here](https://github.com/rdbende/Sun-Valley-ttk-theme/blob/master/theme/light/radio-rest.png) and right clicking image -> save as and replacing it. I'm thinking that some user error (or maybe my old hard drive) caused the local copy to become corrupted.
Apologies for sounding the alarm on this!
