### ISSUE TITLE
Should have Textbox Component

### ISSUE THREAD

**Issue by khanh1104** [rdbende/Sun-Valley-ttk-theme#24]

**Comment by rdbende** [comment]
?

**Comment by rdbende** [comment]
Duplicate of #9

Unfortunately the textbox widget isn't stylable, so this theme can't do anything with it. However you can wrap the `tk.Text` widget into a `ttk.Entry`, and it does kinda what you want.

**Comment by khanh1104** [comment]
> Duplicate of #9
> 
> Unfortunately the textbox widget isn't stylable, so this theme can't do anything with it. However you can wrap the `tk.Text` widget into a `ttk.Entry`, and it does kinda what you want.

ok, thanks
