### ISSUE TITLE
Pyinstaller Problems

### ISSUE THREAD

**Issue by not-nef** [rdbende/Sun-Valley-ttk-theme#25]
I use the module version of this theme in one of my apps, and it all works, as long as i dont compile it. When i compile the app with pyinstaller, i get an error when opening the exe.

![Screenshot 2022-04-16 135324](https://user-images.githubusercontent.com/83908932/163673911-a7b8118f-519f-4490-9de5-a54d14a2eb32.png)

How do i fix this?

**Comment by rdbende** [comment]
Yeah, same here on Linux.
```
Traceback (most recent call last):
  File "FPC.py", line 67, in <module>
    sv_ttk.set_theme("dark")
  File "sv_ttk/__init__.py", line 18, in wrapper
_tkinter.TclError: couldn't read file "/tmp/_MEIhA7lFH/sv_ttk/sun-valley.tcl": no such file or directory
[5417] Failed to execute script 'FPC' due to unhandled exception!
```
Looks like Pyinstaller doesn't include the theme files, only the Python module file. I think it's possible to solve it by editing the `.spec` file, but I'll have to look into it.

**Comment by xiaolovesmall** [comment]
I have the same problem.When i compile the app with pyinstaller, i get an error when opening the exe.

**Comment by not-nef** [comment]
@rdbende Should i open an issue in the pyinstaller repo?

**Comment by sumeshir26** [comment]
I found out the problem. Pyinstaller only includes the .py files when creating the exe so the .tcl and .png files will not get included. This cann be fixed by the -add-data option

**Comment by not-nef** [comment]
I FOUND A FIX GUYS!!!!!!

and yes @sumeshir26 yours didnt work.

everything you have to do, is add the following flag to your pyinstaller command:

`--collect-data sv_ttk`

**Comment by not-nef** [comment]
im so happy
