### ISSUE TITLE
Can you update the 'pressed' state button in light mode to not transparent?

### ISSUE THREAD

**Issue by HuyHung1408** [rdbende/Sun-Valley-ttk-theme#26]
Because the button need to click multiple times before they can be insert into the content. It only happens in light mode because the 'pressed' state in light mode is a bit transparent, but the windows was also transparent for the mica effects so it needs to click multiple times before they can be insert into the content. This does not happen in dark mode, because the 'pressed' state in dark mode is not transparent. 

https://user-images.githubusercontent.com/86362423/164738773-eeb3e5c1-9327-49ff-83a6-482e21669943.mp4

**Comment by rdbende** [comment]
Strange... That image doesn't have any transparency.

**Comment by HuyHung1408** [comment]
> 

yup, I know that's weird, may be I should do sth else I bet, thanks for your response, I'll close this issue for now

**Comment by HuyHung1408** [comment]
> Strange... That image doesn't have any transparency.
 I looked at the original SVG file in Inkscape, and there's no transparency in that image anywhere, so I think the problem here is 
 something else.
 There's no difference between dark and light theme responsiveness on my Linux system. Tk is notoriously bad at displaying png 
 on Windows (due to some Windows API stuff 😕), however I don't know why does it work better with dark theme.

yup, I know that's weird, may be I should do sth else I bet, thanks for your response, I'll close this issue for now
