### ISSUE TITLE
Changing tick mark color

### ISSUE THREAD

**Issue by bascurtiz** [rdbende/Sun-Valley-ttk-theme#27]
Hi!
First of all, I love your themes!
Great work, really well done and easy to alter.

We basically could alter anything we wanted, either editing the .tcl files or overwriting the pngs provided.
But... The tick mark (esp, in dark mode).

Is that something that's part of tKinter or your theme?
I couldn't find a way to alter it.

![image](https://user-images.githubusercontent.com/34075088/165160781-bb647449-3bdf-4df1-a39a-4016fa690d09.png)

As you can see, even in your Simple Example.py the contrast with the dark background is kinda meh.
The tick mark icon next to Option 1, I'm refering to.
I'd love to have it bright, instead of dark for better contrast.

Or... maybe I'm barking up the wrong tree and this is a part of tKinter by default?
If so, do you know what I need to alter?

Thanks in advance!

**Comment by rdbende** [comment]
I've seen, some ttk themes somehow got around this, I'll see, what I can do.
