### ISSUE TITLE
Odd Issue

### ISSUE THREAD

**Issue by DINOTICK-Dev** [rdbende/Sun-Valley-ttk-theme#28]
I am not sure why, but the images for the custom buttons and stuff do not work. The only thing this style changes for me is when I hover over and click a button it turns blue and the background is slightly more gray. On Linux, you can see the entry and buttons as you're supposed to, but only in the file dialog? On windows, nothing works but the slight color changes mentioned earlier. I do not believe this is an issue with my code. I am using the module.

**Comment by rdbende** [comment]
Seems like you're using plain tkinter widgets, that can change only in their colors. Please change them to `ttk` widgets, since only they can be themed.
