### ISSUE TITLE
Looks like puke on Android

### ISSUE THREAD

**Issue by rdbende** [rdbende/Sun-Valley-ttk-theme#29]
Ttk scaling...

![Screenshot](https://user-images.githubusercontent.com/77941087/166223835-ca4659f9-fd66-47c9-bbfa-dda03200a647.png)

**Comment by sumeshir26** [comment]
how did you run tkinter on android???

**Comment by HuyHung1408** [comment]
How can you make tkinter to Android? Looks cool

**Comment by HuyHung1408** [comment]
> how did you run tkinter on android???

Lmao same question 🤣🤣

**Comment by rdbende** [comment]
> how did you run tkinter on android???

[Pydroid](https://play.google.com/store/apps/details?id=ru.iiec.pydroid3) comes with Tkinter built-in.

**Comment by rdbende** [comment]
Actually just a duplicate of #18
