### ISSUE TITLE
Strange dashed line around notebook tab text

### ISSUE THREAD

**Issue by fabian1606** [rdbende/Sun-Valley-ttk-theme#31]
When I create a notebookelement I get a dashed line around the tabs of the notebook. It only appears when i click on the tab and dissapears when I click on another element.
![image](https://user-images.githubusercontent.com/65162268/171417583-b1508aa0-57f1-422e-9bb6-a85d972cbbef.png)
Is there a way to hide this line or can I change the color of it to the backgroundcolor ?

**Comment by rdbende** [comment]
Lol, that "strange blue line" is in fact the the keyboard focus indicator, so I don't recommend to remove it.
But in case you really need, you can hide it by changing the `Notebook.Tab` layout with a `ttk.Style` object.
I can't explain it atm, but you can read about style layouts here: https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/ttk-layouts.html

**Comment by fabian1606** [comment]
I have it now working by adding "takefokus = 'No' " in the definition of every Tab. The only disadvantage I see is that you lose the opportunity to navigate through the tabs with the arrow keys, everything else seems to be the same as before.

**Comment by curtis18** [comment]
If double clicking the tab, the dashed line around the tabs situation still happens.
