### ISSUE TITLE
_tkinter.TclError: couldn't read file "sun-valley.tcl": no such file or directory

### ISSUE THREAD

**Issue by muhammadfaruq72** [rdbende/Sun-Valley-ttk-theme#32]
I've done everything but the problem remains the same USING PYINSTALLER! Any Help?
![Screenshot 2022-06-24 at 12 12 34 PM](https://user-images.githubusercontent.com/51035641/175483194-b27cdd9e-0679-4ce7-bd76-ec72bd94ac0d.png)

**Comment by sumeshir26** [comment]
If you use sv-ttk, add `--collect-data sv_ttk` to the command

**Comment by muhammadfaruq72** [comment]
I installed it using pip install sv-ttk but seems like it is not installed properly. it's not collecting module using --collect-data sv_ttk. Even if I try to run program it shows this error
![Screenshot 2022-06-24 at 12 21 15 PM](https://user-images.githubusercontent.com/51035641/175484640-a74f9782-5a84-4751-9140-e7f9fbfef607.png)
.

**Comment by rdbende** [comment]
But if you use the `sv_ttk` module, you don't need to manually call that `source blablabla`, neither the `set_theme dark`.
Instead you can simply `import sv_ttk` and then use `sv_ttk.use_dark_theme()`. This way it should with Pyinstaller.

**Comment by muhammadfaruq72** [comment]
> `sv_ttk.use_dark_theme()`

It works! Thank you 😇
