### ISSUE TITLE
Add animations for switch

### ISSUE THREAD

**Issue by Fire-Cube** [rdbende/Sun-Valley-ttk-theme#39]
Can you please add animations for the switch and stuff? That would take this project to a new level.

**Comment by rdbende** [comment]
I would have added animations, but Tkinter doesn't support animations of any kind. So I just simply can't.

**Comment by Fire-Cube** [comment]
You could provide the animations so that you can use them something like https://stackoverflow.com/questions/65223063/is-it-possible-to-provide-animation-on-image-tkinter
