### ISSUE TITLE
Checkbutton widget in dark mode problem

### ISSUE THREAD

**Issue by tzdziech** [rdbende/Sun-Valley-ttk-theme#41]
In dark mode I cannot set Checkbutton as selected, the field where the selction mark should be stays empty.
![image](https://user-images.githubusercontent.com/107561635/182714079-ab184e25-68f2-477f-a49f-a28d3295d003.png)

**Comment by rdbende** [comment]
It seems like you're using a plain `tkinter.Checkbutton`, not a `ttk` one, therefore it doesn't get themed. The checkbutton you see is not even affected by the theme.

**Comment by tzdziech** [comment]
@rdbende thank you, you are right.
