### ISSUE TITLE
Window resize slow problum

### ISSUE THREAD

**Issue by sadjok** [rdbende/Sun-Valley-ttk-theme#43]
I opened the program manager, i see when i am resize the window, my CPU using is getting higher, like exponential growth, and the window become laggy...
But the gif branch and make the window good than the png branch, go to see the under of  of Sun-Valley-ttk-theme's markdown file, it has gif branch, or see my project CodeNoteBook, i replace it very successful : every thing become very good, and the scrollbar become good than the png branch.
So, gif branch can save the CPU using, but can make the window beautifully?
Hope the finish the resize problum.
My CPU is “happy"... 👍🏼

**Comment by rdbende** [comment]
I am really sorry, but I don't understand what you are trying to say. What is your issue?

**Comment by sumeshir26** [comment]
i guess they are trying to say that  the PNG branch laggs when resizing, and GIF fixes the issue, but dosent look as good.

**Comment by sumeshir26** [comment]
Never mind, just saw the other issuee

**Comment by rdbende** [comment]
> but dosent look as good.

Hmm, yes... Gif images...
