### ISSUE TITLE
Text background is not white

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#44]
When my editor use sun-valley-ttk theme, i found a bug:
Python:3.9.9, Tcl/Tkinter:8.6, Windows:10
I used idle's highlight, when the highlight work, the highlighted word's background's color is different with the Text() background.
That looks bad.....
This is a bug or just my computer's wrong.
When i "take off" sun-valley-ttk theme, everything goes well, and the highlight color this not different with the Text() background
And use ttk lib isn't effect the Text() color, so i think is theme's wrong.
Can anyone tell me what is the happened.
Thx.
Program original file github.com/sadjok/CodeNoteBook

**Comment by sadjok** [comment]
I tested with anthor file, the problum is the theme.

**Comment by sadjok** [comment]
strange, i change a computer, the Text() color looks not different with highlight background...

**Comment by rdbende** [comment]
So if I understand well, when you select something in the Text widget, its background changes. Right?

**Comment by sadjok** [comment]
em, i mean when the text widget create, the background is different with white.

**Comment by rdbende** [comment]
😵‍💫

**Comment by sumeshir26** [comment]
Could you share a screenshot?

**Comment by sadjok** [comment]
How to show a screenshot
?

**Comment by sumeshir26** [comment]
On your pc press Control + Shift + S and select the area you want to capture, and paste it in the Github Comment box using Control + V

**Comment by rdbende** [comment]
> Control + Shift + S

<kbd>Win + Shift + S</kbd> if you're on Windows, or just simply <kbd>Print screen</kbd>.
