### ISSUE TITLE
The theme not apply correctly

### ISSUE THREAD

**Issue by Fefedu973** [rdbende/Sun-Valley-ttk-theme#48]
why it render like this ?
![image](https://user-images.githubusercontent.com/80718477/191484134-c10bef8d-ae00-4431-a4fa-a0aff73ae716.png)

**Comment by sumeshir26** [comment]
Make sure to use ttk elemenrs, not plain Tk.
Example: Use `tkinter.ttk.Label` instead of `tkinter.Label`
Do this for all witgets ecxcept the main tkinter.Tk window and any tkinter.Toplevel s

**Comment by Fefedu973** [comment]
> Make sure to use ttk elemenrs, not plain Tk. Example: Use `tkinter.ttk.Label` instead of `tkinter.Label` Do this for all witgets ecxcept the main tkinter.Tk window and any tkinter.Toplevel s

ok and now how can i get white theme ?

**Comment by sumeshir26** [comment]
Just put in the line sv_ttk.use_light_theme()
