### ISSUE TITLE
Add support for Scrolled Text

### ISSUE THREAD

**Issue by Fefedu973** [rdbende/Sun-Valley-ttk-theme#49]

**Comment by rdbende** [comment]
What do you mean?

**Comment by Fefedu973** [comment]
This is a tkinter widget

**Comment by Fefedu973** [comment]
https://docs.python.org/fr/3/library/tkinter.scrolledtext.html

**Comment by rdbende** [comment]
Yea, I am aware of that, but what has it got to do with the SV theme? Do you want me to create a style for it?
If yes, it's unfortunately not possible, because it's not a themeable widget :(

**Comment by Fefedu973** [comment]
Oh ok rip tanks anyway
