### ISSUE TITLE
beautify Combobox

### ISSUE THREAD

**Issue by Fire-Cube** [rdbende/Sun-Valley-ttk-theme#51]
Can you please beautify the Combobox. It doesn't fit the rest of the program at all. I would be very happy about that. Thanks in advance.

**Comment by rdbende** [comment]
Uhh. What do you mean?

**Comment by rdbende** [comment]
Ahh, I think I got you. Is the issue with the combobox popdown?

If yes, then the unfortunate truth is that ai cannot beautify it. The combobox is a quite weird widget, it has a stylable button, but a non-stylable popdown with a stylable scrollbar. I can only set colors, and borderwidth on the list, but no any rounded and other fancy styles.

**Comment by Fire-Cube** [comment]
Do you have Discord?

**Comment by Fire-Cube** [comment]
I think I have a solution that I'd like to discuss with you privately.

**Comment by rdbende** [comment]
I don't have Discord. Sorry.

Normally you could chat with me on IRC on the `##learnpython` channel, however I've been quite busy lately, so I'm not able to chat live. So if you want to write me privately, you have to use my email.

Actually, I have an idea to implement a fully-themeable combobox widget, but I do not plan to make it for this theme, only for [`Tukaan`](https://github.com/tukaan/tukaan)
