### ISSUE TITLE
TclError: unknown option "-troughcolor"

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#52]
I was programming a project. I did:

```py
self.tk.call("source", self.path)
self.tk.call("set_theme", "light")
```

And I made a function like this:

```py
def dark_mode(self, sync = True):
    """Turn Program into Dark Mode"""
    if sync:
	self.tk.call("set_theme", "dark")

    DWMWA_USE_IMMERSIVE_DARK_MODE = 20
    set_self_attribute = windll.dwmapi.DwmSetWindowAttribute
    get_parent = windll.user32.GetParent
    hwnd = get_parent(self.winfo_id())
    rendering_policy = DWMWA_USE_IMMERSIVE_DARK_MODE
    value = c_int(2)
    set_self_attribute(hwnd, rendering_policy, byref(value), sizeof(value))
    self["background"] = "black"
```

I want to make the program turn into dark mode, and I want theme into dark mode too.
But I get a error, it is:

```yaml
_tkinter.TclError: unknown option "-troughcolor"
```

How can I change theme when it has already been loaded?

**Comment by sadjok** [comment]
![image](https://user-images.githubusercontent.com/71159641/193812719-503a9782-e7dd-4c29-8c07-1f1486bf5bb1.png)

^
 |

**Comment by rdbende** [comment]
What Tcl and Tk version are you using?

```py
print(f"Tcl: {tkinter.TclVersion}")
print(f"Tk: {tkinter.TkVersion}")
```

**Comment by sadjok** [comment]
![image](https://user-images.githubusercontent.com/71159641/194000479-b5ab50b0-fd84-4f95-b8f2-b5505ea58a08.png)

**Comment by sadjok** [comment]
Tcl & Tk Both 8.6

**Comment by rdbende** [comment]
This is really strange. I cannot reproduce it, and I have never seen anybody with this error.
Does the issue still persist if you use `sv_ttk` instead of this old and discouraged `.tk.call()` method?

**Comment by sadjok** [comment]
okay, i will use sv_ttk

**Comment by sadjok** [comment]
thx

**Comment by sadjok** [comment]
![image](https://user-images.githubusercontent.com/71159641/200104225-4ea20830-5cce-49f1-8cb9-be8f2e6e2610.png)
The problem arises again...
And i use sv_ttk...

**Comment by sadjok** [comment]
script is in my github:[github.com/sadjok/Editor](https://github.com/sadjok/Editor)

**Comment by sumeshir26** [comment]
It looks like you dont use sv_ttk:
![image](https://user-images.githubusercontent.com/68823982/200124258-bf4577a0-5649-425b-8a80-59fadbaacd53.png)
Can you try that?

**Comment by sadjok** [comment]
i just move sv_ttk to my asset folder...
![image](https://user-images.githubusercontent.com/71159641/200163912-b314febe-0833-4736-baa7-cf7f770e0036.png)

**Comment by sadjok** [comment]
asset folder...:
![image](https://user-images.githubusercontent.com/71159641/200164018-ccc1de5f-71b5-48c0-a781-321685fd28eb.png)

**Comment by sadjok** [comment]
sv.tcl & theme.py & theme folder

**Comment by sumeshir26** [comment]
Try installing sv_ttk using `pip install sv-ttk` in your terminal, and then `import sv_ttk` in your code, and then `sv_ttk.use_light_theme()` to start sv_ttk.
Hope this helps.

**Comment by sadjok** [comment]
![image](https://user-images.githubusercontent.com/71159641/201453745-4ceb4dad-5614-4546-a018-102f8b03f6f2.png)
...It.emm.well.i just want to give up now :(

**Comment by sadjok** [comment]
Or, how to make a function like sv_ttk changing the theme for the window every time when I change the theme in the Settings?(Almost sync?)

**Comment by sumeshir26** [comment]
Well maybe require a app restart to chage the theme...
sorry, i cant tkink about any other solutuon :(

**Comment by sadjok** [comment]
Thanks for the answer, sorry for my interruption to you......

**Comment by sadjok** [comment]
Hope who can solve it....
However, i am tired of it, i tried too many times too......
Each time, the same wrong shows.....
