### ISSUE TITLE
Pyinstaller Error

### ISSUE THREAD

**Issue by rohankishore** [rdbende/Sun-Valley-ttk-theme#58]
Getting the error "ModuleNotFoundError: No module named 'sv_ttk'" when trying to open the exe file... 

btw, this's my pyinstaller command: 
''' pyinstaller --onefile -w .\scratch_3.py --hidden-import wikipedia --collect-data sv_ttk  '''

**Comment by rdbende** [comment]
And are you sure, `sv_ttk` is installed, and Pyinstaller can access it? (So for example if you installed it in a virtual environment, Pyinstaller won't be able to collect it, if it's not in the same venv)

**Comment by mscholze** [comment]
Same here. Installed with `pip install sv-ttk` on MacOS Ventura and get `ModuleNotFoundError: No module named 'sv_ttk'` when running the python file.

**Comment by mscholze** [comment]
Okay I figured out that my python installation was broken after upgrading to macos ventura. Had to reinstall python3 via homebrew and reinstalled the module via `pip3 install sv-ttk`. After that everything works as expected.

**Comment by rohankishore** [comment]
Great!! But just dont use Notebook tabs with this theme... Its too slow to load and switch between tabs even though I'm using a fairly good PC with Ryzen 7 5800H and 16gb ram
