### ISSUE TITLE
Dark theme has inconsistent padding compared to light theme

### ISSUE THREAD

**Issue by PicoPlanetDev** [rdbende/Sun-Valley-ttk-theme#6]
![LightDarkDiscrepancy](https://user-images.githubusercontent.com/50522829/134018082-8e3cfa5e-736a-403f-a553-0577cda44376.gif)

If you look closely at the titlebar in my demo window, the "b" becomes slightly more cut off than in light theme after the theme switches to dark. It appears to be affecting both the horizontal and vertical padding/margin, because more complex windows with vertically stacked items also results in the labels pushing the rest of the content down. Here is an example from another project I am working on:
![SizingIssueLightDark](https://user-images.githubusercontent.com/50522829/134018756-66dc0a1d-b1b8-4cb4-82b6-d87577353a4e.gif)

I have skimmed through the light and dark tcl themes but haven't found anything that might cause this.

**Comment by rdbende** [comment]
I can't find anything, that might cause this issue, so I think, it's an issue with ttk itself. Also, if you have treeview in your GUI, the resizing is more radical.

**Comment by PicoPlanetDev** [comment]
Thank you for checking on this. I do not have a treeview anywhere, it looks like it is just the label widgets themselves. I will experiment with manually setting padding and see if I can come up with anything else that may help reproduce this issue.

**Comment by rdbende** [comment]
Strange, but I can't find anything related to it.

https://user-images.githubusercontent.com/77941087/147226928-d2c7fa7d-0b26-4d35-9e8b-90e2210bd338.mp4

**Comment by rdbende** [comment]
Ahh, found
https://github.com/rdbende/Sun-Valley-ttk-theme/blob/bd2ac1d925855666366b2da9f2f9e40af3af0f97/sun-valley.tcl#L31
vs
https://github.com/rdbende/Sun-Valley-ttk-theme/blob/bd2ac1d925855666366b2da9f2f9e40af3af0f97/sun-valley.tcl#L71

I put it there, because I needed a 1px border for the Combobox dropdown, in the meantime I realized that there is a `ComboboxPopdownFrame`, but I forgot to change this back to 0.

**Comment by PicoPlanetDev** [comment]
Oops, that would explain it! Thank you so much, I will update my applications that make use of this awesome theme.
