### ISSUE TITLE
Change font to Segoe UI Variable Text/Display

### ISSUE THREAD

**Issue by martinet101** [rdbende/Sun-Valley-ttk-theme#61]
Windows 11 uses the following fonts for UI:
 - `Segoe UI Variable Text` for body text
 - `Segoe UI Variable Display` for titles

Would it be possible to add those fonts to sv_ttk so it looks more integrated?

**Comment by rdbende** [comment]
Hi! Thank you for checking out my theme!

Sure, I'll add them to sv-ttk, though the only place I feel `Segoe UI Variable Display` should be set by the theme is labelframe titles, because for other headers and title labels the user will set the font separately anyway (or maybe include a style for titles, so they look consistent everywhere?).

**Comment by martinet101** [comment]
For titles, i'd even go with `Segoe UI Variable Display Bold`, using a consistent style,

**Comment by martinet101** [comment]
Also, there's a python library made to apply mica effect on tkinter windows, would you be interested on it or it'd be out of scope for this project?

**Comment by rdbende** [comment]
Thanks for this suggestion! It's now in f54671d

> Also, there's a python library made to apply mica effect on tkinter windows, would you be interested on it or it'd be out of scope for this project?

I think mica support is out of the scope of this project, and if somebody wants to use it, they can install `win32mica` separately.

**Comment by martinet101** [comment]
Thanks!

One little thing:as of my experience with faking winui styles, I reckon size 9pt for text looks better that 10pt.

Anyway, thanks for the amazing job!

**Comment by rdbende** [comment]
[MSDN](https://learn.microsoft.com/en-us/windows/apps/design/signature-experiences/typography) says 14 points for body text

**Comment by martinet101** [comment]
Oh, I said nothing then. 

Thank you a lot!

**Comment by rdbende** [comment]
742d545
