### ISSUE TITLE
Default behavior of the checkbutton

### ISSUE THREAD

**Issue by foozzi** [rdbende/Sun-Valley-ttk-theme#65]
OS: Fedora 37 (Gnome 43)
Python: 3.11 
Theme: 2.4

```python
import tkinter
from tkinter import ttk

import sv_ttk

root = tkinter.Tk()

button = ttk.Checkbutton(root, text='test')
button.pack()

# This is where the magic happens
sv_ttk.set_theme("dark")

root.mainloop()
```

![Снимок экрана от 2022-12-15 14-55-10](https://user-images.githubusercontent.com/1178208/207864371-2bc91b2b-0f8f-435e-bcbb-1c77fab76a27.png)

I can't remove 'minus' by default

**Comment by rdbende** [comment]
This is the default behavior of the ttk checkbutton. If you don't explicitly set a value for it (usually through a control variable), it will be neither checked nor unchecked, but it will appear in this alternate, "third" state.

**Comment by foozzi** [comment]
> This is the default behavior of the ttk checkbutton, regardless the theme. If you don't explicitly set a value for it (usually through a control variable), it will be neither checked nor unchecked, but it will appear in this alternate, "third" state.
> 
> And oh wait, Fedora has Python 3.11 already? Then I should update mine, it's still 3.10 :)

Thank you! I will try it.


And yes, fedora 37 already has python 3.11) see also https://docs.fedoraproject.org/en-US/fedora/latest/release-notes/developers/Development_Python/
