### ISSUE TITLE
Default font looks ugly in Arabic

### ISSUE THREAD

**Issue by youssefhoummad** [rdbende/Sun-Valley-ttk-theme#66]
The default font looks ugly in arabic
How do I change it?

![لقطة شاشة_20221216_172638](https://user-images.githubusercontent.com/25711246/208144379-fa13edcc-c599-483d-85c3-69893fa53d8f.png)

**Comment by rdbende** [comment]
Hi! You can change the default fonts like this:

```python
from tkinter import font

font.nametofont("SunValleyBodyFont").configure(family="Noto Naskh Arabic")
font.nametofont("SunValleyBodyStrongFont").configure(family="Noto Naskh Arabic", weight="bold")
```

These are the only font styles used by the theme itself, however the theme defines some more fonts that an application might need. Here's a full list of them:
- `SunValleyCaptionFont`
- `SunValleyBodyFont`
- `SunValleyBodyStrongFont`
- `SunValleyBodyLargeFont`
- `SunValleySubtitleFont`
- `SunValleyTitleFont`
- `SunValleyTitleLargeFont`
- `SunValleyDisplayFont`

**Comment by youssefhoummad** [comment]
> Hi! You can change the default fonts like this:
> 
> ```python
> from tkinter import font
> 
> font.nametofont("SunValleyBodyFont").configure(family="Noto Naskh Arabic")
> font.nametofont("SunValleyBodyStrongFont").configure(family="Noto Naskh Arabic", weight="bold")
> ```
> 
> These are the only font styles used by the theme itself, however the theme defines some more fonts that an application might need. Here's a full list of them:
> 
> * `SunValleyCaptionFont`
> * `SunValleyBodyFont`
> * `SunValleyBodyStrongFont`
> * `SunValleyBodyLargeFont`
> * `SunValleySubtitleFont`
> * `SunValleyTitleFont`
> * `SunValleyTitleLargeFont`
> * `SunValleyDisplayFont`
thanks
