### ISSUE TITLE
Low-DPI Issues

### ISSUE THREAD

**Issue by Pololot64** [rdbende/Sun-Valley-ttk-theme#69]
Hey. This is a great project. I have been tinkering around with it and realized that it breaks on low-dpi as well as high (though it is already documented that it breaks on hi-dpi). Is there a way of mitigating this in my code or is it just a work in progress for sv-ttk?

**Comment by littlewhitecloud** [comment]
what does the "break" mean?

**Comment by Pololot64** [comment]
By breaks I mean that when the fonts and buttons scale down to the lower density, the checkbuttons and radiobuttons stay one size:  
![image](https://user-images.githubusercontent.com/31389383/209567620-e1213edb-ab08-41e8-8689-55baacbaaefe.png)

**Comment by rdbende** [comment]
#18
