### ISSUE TITLE
anchor=center attribute in button not working

### ISSUE THREAD

**Issue by zerozedsc** [rdbende/Sun-Valley-ttk-theme#7]
I already use style to center the text in the button, but the text cant be aligned to the center, can I know how to do so with your theme? sorry for opening this issue

**Comment by RGerculy** [comment]
Hi, your issue is very vague, can you add more details? Which layout manager are you using in your application? Maybe include some code as well.

**Comment by zerozedsc** [comment]
I'm using pack layout, but when I'm using tk.Button the text-align well at the center. so maybe ttk.button does not align all text even after \n at the center. 

This is my code:
`button_1 = ttk.Button(self.left, text="ABCDEFGHIJKLMNOP\nQRSTUVWXYZ", width=int(W_LEFT/8), command=None, style=style1)
 button_1.pack(fill='x', anchor=CENTER, pady=1)`

**Comment by RGerculy** [comment]
Had to modify the code a little but I hope it still works for you.
```
        button_1 = ttk.Style()
        button_1.configure('Button1.TButton', justify='center')
        button_1 = ttk.Button(frame, text="ABCDEFGHIJKLMNOP\nQRSTUVWXYZ", width=8, command=None, style='Button1.TButton') 
        button_1.pack(fill='x', anchor=CENTER, pady=1)
```
![button1](https://user-images.githubusercontent.com/25263251/142435602-b81a1067-365f-4118-a7a9-5f61547d84c0.png)

**Comment by zerozedsc** [comment]
yes, it works now. thank you. but why when using anchor=CENTER nothing happen with ttk.button. when using it on tk.button, it works well

**Comment by RGerculy** [comment]
I noticed that as well when testing your code unfortunately that is beyond my abilities. Hopefully somebody else will be able to address that issue.

**Comment by zerozedsc** [comment]
> I noticed that as well when testing your code unfortunately that is beyond my abilities. Hopefully somebody else will be able to address that issue. 

Okey, thank you for helping me. I think i will close this issue, because it is not a big issue at all
