### ISSUE TITLE
Disabled Widgets are not immediately identifiable from Enabled widgets...

### ISSUE THREAD

**Issue by TheWicklowWolf** [rdbende/Sun-Valley-ttk-theme#71]
**With normal ttk the disabled widgets are easily distinguishable:**

![image](https://user-images.githubusercontent.com/111055425/217518318-7c70b2bb-30c1-440f-b3ce-05dd074b9be0.png)

---
**With Sun-Valley:**

![sv](https://user-images.githubusercontent.com/111055425/217517166-36a28b2d-af90-459e-9ab6-c9da17661c83.PNG)

---
With Azure:

![Azure](https://user-images.githubusercontent.com/111055425/217517279-063b78a0-4c44-403e-9448-fffaea0477e7.PNG)

---
With Forest:

![Forest_ttk](https://user-images.githubusercontent.com/111055425/217517315-ab402a43-f097-4775-ad0c-639ee0b64e50.PNG)

___

This is a very good library!
Is there any way to make it easier to see which widgets are disabled?

**Comment by TheWicklowWolf** [comment]
Just to narrow it down, the Entry Box probably has the least difference between enabled and disabled...

**Comment by rdbende** [comment]
Thank you for reporting this. It's now fixed for the Sun Valley theme.

**Comment by rdbende** [comment]
![image](https://user-images.githubusercontent.com/77941087/226110101-e58fcbb4-1d74-47a8-bef0-302e2c617694.png)
