### ISSUE TITLE
Theme not applying when tk instance changes

### ISSUE THREAD

**Issue by ilya12077** [rdbende/Sun-Valley-ttk-theme#72]
Hi, love your theme. I'm not sure if there is my mistake in code since i've just started to learn tk but it seems ok

# Problem
I'm using python 3.10 and sv-ttk 2.4.3. I have two windows with different tk instances. After I apply theme to the first window and destroy it, I can't use your theme in other windows.
![1](https://user-images.githubusercontent.com/52870065/229289265-d1228610-117f-4a41-87e7-1ee4ddb206b5.png)
![2](https://user-images.githubusercontent.com/52870065/229289268-a89f37f5-ccd6-423e-9746-66fdbb2e78b2.png)

New window will have tk default theme and applying your theme on new window raises:
```
Traceback (most recent call last):
  File "**\test.py", line 29, in <module>
    sv_ttk.set_theme("dark")  #gives error
  File "**\Python\Python310\lib\site-packages\sv_ttk\__init__.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "**\Python\Python310\lib\site-packages\sv_ttk\__init__.py", line 41, in set_theme
    root.tk.call("set_theme", theme)
_tkinter.TclError: can't invoke "winfo" command: application has been destroyed
```
**Code to reproduce**
```
from tkinter import *
from tkinter import ttk
import sv_ttk

root = Tk()
root.geometry('450x110')
root.title("Fisrt window")
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)
mainframe = ttk.Frame(root)
mainframe.grid()

ttk.Button(mainframe, text="Destroy first", command=root.destroy).grid()
sv_ttk.set_theme("dark")
root.mainloop()


new_root = Tk()
new_root.geometry('450x110')
new_root.title("Second window")
new_root.columnconfigure(0, weight=1)
new_root.rowconfigure(0, weight=1)
mainframe = ttk.Frame(new_root)
mainframe.grid()

ttk.Button(mainframe, text="Destroy second", command=new_root.destroy).grid()
#sv_ttk.set_theme("dark")  # gives error
new_root.mainloop()
```
# Workaround
I've found simple solution for me but i guess this cannot be used in production. In *sv_ttk\__init__.py* in *line 14* change `if not inited:` to `if True:` so it query fresf tk instance every time

**Comment by rdbende** [comment]
Hi! Thanks for using this theme!

This behavior is intentional, as I couldn't think of any scenarios where people would want to use multiple `Tk` instances in the same program (and they shouldn't).
The second `Tk` instance initializes a new embedded Tcl interpreter, that **doesn't know anything** about the previous `Tk` instance, so the theme won't be applied to its root window. And since `sv_ttk` doesn't know, that the previous `Tk` instance was destroyed, and another created, it tries to set the theme on the first instance, and throws an error, since it no longer exists.

Obviously it's not great, that it completely breaks this way, and doesn't give any useful information. That should be fixed.

My question would be why do you need multiple 'Tk' instances?

**Comment by ilya12077** [comment]
I have the main window with options and buttons to run different scripts. Since these scrits use different window properties I first destroy main one and then create new clean window(and tk instance) to start with, so i dont forget to change something that I needed in main window but not in the second. For example main window was set to be always on top and i dont need this in other scripts. What's the right way to do this?

**Comment by rdbende** [comment]
So if I understand well, you want to launch totally different scripts from the main window, and then hide the main window. In this case I would use `subprocess.Popen` to execute a separate Python file, and that way it can have its own root window.
Note that even Tkinter can misbehave if there are multiple root windows in the same program (even if the first is destroyed).

**Comment by ilya12077** [comment]
Ok thanks for advise!
