### ISSUE TITLE
packing error with pyinstaller 

### ISSUE THREAD

**Issue by shandy7** [rdbende/Sun-Valley-ttk-theme#86]
Hi rdbende 
 i tried creating a exe for my python code with sun valley theme . I am using auto-py-to-exe to create the exe file.  i have added the theme using collect data but on opening the exe file i get the following error.

Traceback (most recent call last):
  File "Interlock.py", line 107, in <module>
  File "sv_ttk\__init__.py", line 19, in wrapper
_tkinter.TclError: couldn't read file "C:\Users\X0132832\AppData\Local\Temp\_MEI197282\sv_ttk\sv.tcl": no such file or directory

**Comment by rdbende** [comment]
So the solution in #38 doesn't work for you.

Some Windows and Pyinstaller experts needed. I have no idea about this 🤷

**Comment by ThatRandomCeltic** [comment]
@shandy7 I was able to make it work using this exact PyInstaller command on Windows:

`py -m PyInstaller --onefile --collect-data sv_ttk CalculatorApp.pyw`

This is the same solution as shown in #38 so maybe it won't help but I was having the exact same error as you before I tried this.

**Comment by lmjaedentai** [comment]
Same here #38 doesnt works for me
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/63090071/d90792ee-1633-47e2-bdd1-2dc17acc5213)

**Comment by lmjaedentai** [comment]
Make sure the `sv_ttk` not only installed in the specific venv, but also your global python environment

**Comment by mak448a** [comment]
Try adding the package to your app.spec file e.g. in the `datas=[]` list

**Comment by neongel** [comment]
Oh，You need to add this parameter after pyinstaller:--collect-data sv_ttk

**Comment by Andrew-J-Larson** [comment]
If you're installing `sv_ttk` inside a `.venv`, then you also need to make sure that `pyinstaller` is installed and launched from within the same `.venv`, along with all other packages that you need for your application.

Never launch `pyinstaller` as global, that will take ALL packages that you've installed to your system, and package it with your app (depending on how good the auto trimming is, might take a good chunk of it away though, but still ill advised to run as global).
