### ISSUE TITLE
Small question about the license

### ISSUE THREAD

**Issue by Yusuf-YENICERI** [rdbende/Sun-Valley-ttk-theme#88]
I have read on reddit that license of that project is GPL 3 even though it obviously says MIT here. Which is the real?

https://www.reddit.com/r/Python/comments/liytrm/modern_ttk_theme/

**Comment by rdbende** [comment]
It's MIT. That theme on Reddit is [another](https://github.com/rdbende/Azure-ttk-theme)  theme, that _was_ GPL 3, but even it was relicensed to MIT.

**Comment by Yusuf-YENICERI** [comment]
Thank you so much for the fast reply.
