### ISSUE TITLE
sv_ttk does not work when used with tkinter.NoDefaultRoot().

### ISSUE THREAD

**Issue by CallMePixelMan** [rdbende/Sun-Valley-ttk-theme#91]
Hello,

As tkinter default roots system could lead to some problems, I use `tkinter.NoDefaultRoot()` quite often in order to always keep a strong link between my Tk and my toplevels.

As `sv_ttk` uses the the tkinter's `_default_root` global variable in order to apply the style, I think it would be better to add an optional parameter (such as `set_theme(theme: string, root: tkinter.Tk | tkinter.TopLevel)`) in order to be able to apply the style to any window object without using any side effect. `use_dark_theme(root)` and `use_light_theme(root)` could work the same. 
In my opinion it would be a better way of applying styles when using a class based GUI, for example;
```py
class MyTopLevel(tkinter.TopLevel):
    def __init__(self, master):
        super().__init__(master=master)
        sv_ttk.use_dark_theme(self)
```

Thanks

**Comment by rdbende** [comment]
Hi,

Honestly I've never seen anyone disabling the default root feature, but I understand your request, and I will add this option ASAP.

**Comment by CallMePixelMan** [comment]
Hello, thanks for your changes :)

I don't use NoDefaultRoot() often, but when you have a lot of windows, have a mandatory link between each window is important to have a explicit hierarchy. Thanks again 👍🏻
