### ISSUE TITLE
```window.option_add("*font", ...)``` doesn't effect some buttons

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#93]
![image](https://github.com/littlewhitecloud/TkTerminal/assets/71159641/09a53045-8806-4e63-9045-741bcce65e99)

@rdbende, is this a bug or there is something wrong with my code, I used 
```python
config.option_add("*font", ("Cascadia Mono", 9))
```
to set the windows's font but it doesn't effect two buttons in the bottom.
Code: [style.py](https://github.com/littlewhitecloud/TkTerminal/blob/main/tktermwidget/style.py)

**Comment by rdbende** [comment]
The font of those buttons is definitely weird, but it's not the default, so _something_ is working.

**Comment by littlewhitecloud** [comment]
> The font of those buttons is definitely weird, but it's not the default, so _something_ is working.

Do you mean the buttons in the red circle? ? It maybe because Windows10 doesn't have a correct Segoe UI font...

**Comment by littlewhitecloud** [comment]
Yes, I think.

**Comment by littlewhitecloud** [comment]
It seems that the ```ttk.Button``` widget doean't follow the ```window.option_add("*font", ...)```

**Comment by rdbende** [comment]
That's quite unlikely, because it does for me.
However, why don't you use a `ttk.Style` for configuring the font of the button? Is it not working either?

**Comment by littlewhitecloud** [comment]
Yes.

**Comment by rdbende** [comment]
Can you show a screenshot with this line commented out, and another one with the font set to something other than `Cascadia Mono`?

**Comment by littlewhitecloud** [comment]
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/0379d172-e289-4c97-a5a3-b6537ced768b)
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/2c2ca7a6-c736-4e81-978e-0c86edb676f3)

**Comment by rdbende** [comment]
Wait, comparing these last two screenshots to the first one, it appears, that your font actually gets applied to those buttons, even though it looks a bit bad.

**Comment by littlewhitecloud** [comment]
LOL, it is still the default font.

**Comment by littlewhitecloud** [comment]
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/8dae714b-4432-4ff2-a717-d9feff005835)
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/ec0b54c6-458d-4ad4-8a5c-03c2be7dc52b)

**Comment by littlewhitecloud** [comment]
Seems that button doesn't follow the settings

**Comment by littlewhitecloud** [comment]
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/a08642a4-9426-4258-be83-304ad09642d8)

forget to say that I am using sv_ttk 2.0 and after I upgrading to 2.5.3, It looks more bad
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/5a72c999-1bf3-4da3-8c6f-179ccc4cdfab)

**Comment by littlewhitecloud** [comment]
It seems that sv_ttk 2.0 still can show Seoge UI font correctly on Windows 10......

**Comment by rdbende** [comment]
> after upgrading to 2.5.3, it looks worse

In what aspect?

> Seems that button doesn't follow the settings

What settings? You just proved, that
```py
config.option_add("*font", ("Cascadia Mono", 9))
```
actually changes the font:

With default font
![image](https://user-images.githubusercontent.com/71159641/252143189-8dae714b-4432-4ff2-a717-d9feff005835.png)

with your `Cascadia Mono` font:

![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/77941087/ed5887e3-19bf-47f7-8370-314f863e814b)

**Comment by rdbende** [comment]
> It seems that sv_ttk 2.0 still can show Seoge UI font correctly on Windows 10......

I can't understand why the same font is called differently on Windoze 10 and 11
Will fix that.

**Comment by littlewhitecloud** [comment]
> > after upgrading to 2.5.3, it looks worse
> 
> In what aspect?
> 
> > Seems that button doesn't follow the settings
> 
> What settings? You just proved, that adding
> 
> ```python
> config.option_add("*font", ("Cascadia Mono", 9))
> ```
> 
> actually changes the font:
> 
> With default font ![image](https://user-images.githubusercontent.com/71159641/252143189-8dae714b-4432-4ff2-a717-d9feff005835.png)
> 
> with your `Cascadia Mono` font:
> 
> ![image](https://user-images.githubusercontent.com/77941087/252144587-ed5887e3-19bf-47f7-8370-314f863e814b.jpeg)

No, actually, it is still the consolation font with the latest screenshot.

**Comment by littlewhitecloud** [comment]
Any font will fail to apply the button
