### ISSUE TITLE
Is there anyway to make the button show the icon's color?

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#96]
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/573b9bf1-8ea2-4d9e-a2dd-bc4a80f3976a)
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/fe5c05b3-71af-410f-9c2c-7385320cc1ff)
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/bb29d91a-40f4-49b3-a10f-35e283d69b9c)
```python
from tkinter import Tk
from tkinter.ttk import Button
from sv_ttk import set_theme

window = Tk()
set_theme("light")
button = Button(window, text = "🎨")
button.pack()
window.mainloop()
```

**Comment by rdbende** [comment]
This isn't really related to the theme, but simply that Tk doesn't really support emojis in general. Try using a png instead.

**Comment by littlewhitecloud** [comment]
@rdbende 
Can you tell me how do you make this?
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/5b3c04b1-0686-4c2a-80e8-5ecf7ae6287d)

**Comment by rdbende** [comment]
That's a PNG image

**Comment by littlewhitecloud** [comment]
> That's a PNG image

Thank you.
