### ISSUE TITLE
module 'tkinter' has no attribute '_get_default_root'

### ISSUE THREAD

**Issue by littlewhitecloud** [rdbende/Sun-Valley-ttk-theme#98]
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/72711602-f066-4fd0-aa28-00266e1975d1)

**Comment by littlewhitecloud** [comment]
python 3.9.0
tkinter 8.6
It seems that tkinter in python 3.9.0 removed _get_default_root

**Comment by rdbende** [comment]
`_get_default_root` was literally just added in 3.9

Your Python installation seems very broken after seeing #52 , #93 and this

> From where did you install it?

> Have you tried reinstalling it?

**Comment by littlewhitecloud** [comment]
Fine I tested on my another computer, it still fails
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/5a16c2a0-8c47-4bc9-9660-e07cebf69615)
![image](https://github.com/python/cpython/assets/71159641/7c9c0c58-9d9d-4740-bf8b-6977d7ddabe3)
There is no ```_get_default_root ```function in the python 3.9.0
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/7ce64e93-7c8f-4e8d-8240-34249b2dd3f0)

After checking the ```__init__.py``` of tkinter in python 3.8.0, it still doesn't have ```_get_default_root``` function.
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/cf9f67b0-ba8a-46d0-8753-7610486775b9)
> Also 3.9.14 doesn't have _get_default_root function

But there is ```_get_default_root``` function in python 3.10
![image](https://github.com/rdbende/Sun-Valley-ttk-theme/assets/71159641/02184945-e7ff-4a73-9a3a-1c23821b0ab9)

**Comment by littlewhitecloud** [comment]
Maybe we should set the version numver to the ```(3, 10)```

**Comment by littlewhitecloud** [comment]
If I can maybe I will make a pr to  fix it. (even it is really small)

**Comment by littlewhitecloud** [comment]
see #99

**Comment by littlewhitecloud** [comment]
@rdbende Can you check it out? I think I am already fix it... (#99)

**Comment by rdbende** [comment]
v2.5.2 is now on Pypi. Thanks!
